platform :ios, '9.0'

target 'I Have More Money Than' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for I Have More Money Than

	pod 'SVProgressHUD'



  target 'I Have More Money ThanTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'I Have More Money ThanUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
